services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SiY5Qj4AidNklPD
      MYSQL_DATABASE: TeamsToDoDB
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - taskly-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 5173:5173
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DISPLAY: ":0"
      DUSK_DRIVER_URL: http://selenium:4444/wd/hub
    networks:
      - taskly-network
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/local/bin/wait-for-it.sh db --  \
        php artisan key:generate
        curl selenium:4444
        php artisan migrate --force
        php artisan db:seed --force
        php artisan test && php artisan dusk

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    ports:
      - 4444:4444
    networks:
      - taskly-network


networks:
  taskly-network:
    driver: bridge

volumes:
  db-data:
    driver: local
