services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: SiY5Qj4AidNklPD
      MYSQL_DATABASE: TeamsToDoDB
    networks:
      - taskly-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - taskly-network

networks:
  taskly-network:
    driver: bridge
